### PR TITLE
Show READMEs on directory index

### PR DESCRIPTION
**Pull request by timdorr**
If there is a Readme file of some sort, this shows it after parsing through [the same Markdown parsing that npm uses](https://www.npmjs.com/package/marky-markdown). 

Highlighting is styled to match the Github aesthetic, but that can be changed if there's something that better suits your preferences.

### CODE REVIEW

**Comment by timdorr** [comment]
*poke* Anything wrong with this as-is? Anything I can do to be helpful?

**Comment by nkbt** [comment]
I think there is no "directory index" thing. if you request component it will serve whatever is set in `packageJson.main`.

**Comment by timdorr** [comment]
Nope, just add a trailing slash: https://unpkg.com/react@15.3.2/

**Comment by nkbt** [comment]
looks like a bug =)

**Comment by nkbt** [comment]
Or not... Sounds like a good addition to render Readme.md under that file list.

**Comment by mjackson** [comment]
I'd rather not serve HTML from unpkg.com because it opens the door for people to run JavaScript on our domain and do all sorts of crazy stuff. At one point I was actually rendering HTML pages in people's packages, but I [had to disable it](https://github.com/unpkg/npm-http-server/blob/561449c8622627402d4e1890cca8744d8ec0d22e/modules/ResponseUtils.js#L64). :/

**Comment by timdorr** [comment]
The [default options](https://github.com/npm/marky-markdown/blob/master/README.md#options) are set to scrub scripts and such. npmjs.org has to deal with the same set of concerns, so this entirely adopts their battle-tested security policies.

**Comment by mjackson** [comment]
Good point, @timdorr. I'll take a closer look here. Sorry for the delay.

**Comment by timdorr** [comment]
No worries and no rush. This is a bonus feature more than anything :)

**Comment by mjackson** [comment]
Thanks for the work here, @timdorr. I really appreciate it.

I think I'd rather leave READMEs to sites like GitHub and npmjs.com, and just focus on serving files. The only reason I made that index page was so I could see what files are in a package and click around and explore. The README on the page is a little distracting from this purpose.

I'm going to close for now, but if we ever feel like adding this feature in the future we know where to start :)

**Pull request closed without merging**
