### PR TITLE
prefix req.baseUrl to redirect location

### PR DESCRIPTION
**Pull request by tarun**
#50  prefix req.baseUrl to redirect location, thus supporting prefixed paths

### CODE REVIEW

**Comment by mjackson** [comment]
Are you using this as middleware within some other app?

**Comment by mjackson** [comment]
Ah, I see. `req.baseUrl` is an express thing. I'd suggest you try to intercept the redirect in your express app instead of us incorporating express-specific code here. Is there a way you can do that? Nothing else in this package is specific to express.

**Comment by tarun** [comment]
Yes, I am using this as middleware in some other app.

I understand the framework agnostic argument.

How about specifying a urlPrefix as a configuration option?
That makes integration much simpler, compared to the alternatives

Because _sendRedirect_ calls _res.writeHead_ and _res.end_ - 
we cannot easily capture it in another middleware function downstream.
Will have to either proxy the call or overwrite res.end/writeHead functions.

**Comment by mjackson** [comment]
Hmm, seems difficult to use a configuration option because those are all provided up front when you first use the middleware. :/

Maybe the easiest thing to do is to just merge this with a comment about how that line is particular to Express...

**Comment by tarun** [comment]
I spun up a standalone server (for different internal reasons), and technically don't encounter this issue anymore...

I will leave it upto your judgement - whether to proceed with this or skip it for now, until others report a similar problem...

As for providing a configuration option - even though the baseUrl can be request specific - it is in most cases static - and sendRedirect can just add it as a prefix.

**Comment by mattdsteele** [comment]
@tarun Reporting a similar problem :)

My use case is similar - we'd like to have our server respond to URLs with a prefix, not at the root of the server. My current plan is to fork, and add a `prefix` configuration option as mentioned, defaulting to `/`.

If you'd like this as a separate PR let me know!

**Comment by mjackson** [comment]
I'm starting to think that maybe being framework agnostic isn't that great. When it comes to managing the base URL, you're essentially talking about routing, which everyone does a bit differently. But it's a crucial part of routing, so we might as well just come out and say "we're an express middleware" and just deal with it.

**Pull request merged**
